// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZZdjE0GJiBvzh9I6n2oa-ACGco6h5e7Y',
    appId: '1:60160576123:web:cc512ed22729243a9f30de',
    messagingSenderId: '60160576123',
    projectId: 'e-auction-1997',
    authDomain: 'e-auction-1997.firebaseapp.com',
    storageBucket: 'e-auction-1997.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZddz7eCuZaqlhfpTnly90XypvScmx3vo',
    appId: '1:60160576123:android:5fe73de85196b6df9f30de',
    messagingSenderId: '60160576123',
    projectId: 'e-auction-1997',
    storageBucket: 'e-auction-1997.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe9tVav3KLkCsavC4jIbcVHRHt3h-nr1A',
    appId: '1:60160576123:ios:a80f3126e149372a9f30de',
    messagingSenderId: '60160576123',
    projectId: 'e-auction-1997',
    storageBucket: 'e-auction-1997.appspot.com',
    iosClientId: '60160576123-fsgq2j0mlgnafk7sogj4gukri4cr9mjv.apps.googleusercontent.com',
    iosBundleId: 'com.ssquare.eAuction',
  );
}
